<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<!DOCTYPE boutique[
	<!ELEMENT boutique (telephone*)>
	<!ELEMENT telephone (marque,modele)>
	<!ELEMENT marque (#PCDATA)>
	<!ELEMENT modele (#PCDATA)>
]>

<boutique>
	<telephone>
		<marque>Sumsung</marque>
		<modele>Galaxy S7</modele>
	</telephone>

	<telephone>
		<marque>Infinix</marque>
		<modele>HOT 4</modele>
	</telephone>

	<telephone>
		<marque>Windows Lumia</marque>
		<modele>5462</modele>
	</telephone>
</boutique>
